stages:
  - environment
  - lint
  - build_debug
  - base_tests
  - device_tests
  - build_release
  - release
  - deploy_staging
  - deploy_production
  # - deploy

.updateContainerJob:
  image: docker:stable
  stage: environment
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

updateContainer:
  extends: .updateContainerJob
  only:
    changes:
      - Dockerfile

ensureContainer:
  extends: .updateContainerJob
  allow_failure: true
  before_script:
    - "mkdir -p ~/.docker && echo '{\"experimental\": \"enabled\"}' > ~/.docker/config.json"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # Skip update container `script` if the container already exists
    # via https://gitlab.com/gitlab-org/gitlab-ce/issues/26866#note_97609397 -> https://stackoverflow.com/a/52077071/796832
    - docker manifest inspect $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG > /dev/null && exit || true
  except:
    changes:
      - Dockerfile

lintDebug:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: lint
    # before_script:
    #   - chmod +x gradlew
    #   - "export VERSION_CODE=$(($CI_PIPELINE_IID)) && echo $VERSION_CODE"
    #   - "export VERSION_SHA=`echo ${CI_COMMIT_SHA:0:8}` && echo $VERSION_SHA"
    # - export JAVA_HOME=/usr/local/openjdk-8
  # - export PATH=$PATH:/usr/local/openjdk-8/bin/java
  script:
    # - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
    - echo 1

assembleDebug:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build_debug
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew assembleDebug
    - echo 1
  # artifacts:
  #   paths:
  #   - app/build/outputs

debugTests:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: base_tests
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:testDebug
    - echo 1

unitTest:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: base_tests
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:test
    - echo 1

andoidTest:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: base_tests
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:connectedAndroidTest
    - echo 1

.device_test_template: &adroid_test
  script:
    # - mkdir build_${release}_${arch}
    # - cd build_${release}_${arch}
    # - schroot -c Ubuntu_${release}_${arch}_ribuilder -- cmake .. -DCMAKE_BUILD_TYPE=Release
    # - schroot -c Ubuntu_${release}_${arch}_ribuilder -- make -j
    - echo "Model ${model} with android ${android_version} testing SUCCESS"

galaxy_7_android_8:
  stage: device_tests
  variables:
    model: "Samsung Galaxy S7"
    android_version: "8"
  <<: *adroid_test

galaxy_10_android_9:
  stage: device_tests
  variables:
    model: "Samsung Galaxy S7"
    android_version: "8"
  <<: *adroid_test

galaxy_20_android_9:
  stage: device_tests
  variables:
    model: "Samsung Galaxy S7"
    android_version: "8"
  <<: *adroid_test


buildRelease:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build_release
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:connectedAndroidTest
    - echo 1

release:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: release
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:connectedAndroidTest
    - echo 1

deployStaging:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy_staging
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:connectedAndroidTest
    - echo 1

deployProduction:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy_production
  # before_script:
  #   - chmod +x gradlew
  script:
    # - ./gradlew -Pci --console=plain :app:connectedAndroidTest
    - echo 1
  rules:
    - when: manual

# deploy:
#   image: maven:3.3.9-jdk-8
#   stage: deploy
#   script:
#     - 'cp ci_settings.xml /root/.m2/settings.xml'
#     - 'mvn deploy'
#   only:
#     - master
